version: '3.1'

services:
  db-client:
    container_name: db-client
    image: postgres:12-alpine
    networks:
      - bcb-nt
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: root
      POSTGRES_DB: clients
    ports:
      - "5432:5432"


  client-ms:
    image: welldefassio/clientes-ms:tagname
    networks:
      - bcb-nt
    ports:
      - "8080:8080"
    environment:
      CLIENT_DB: db-client
    depends_on:
      - db-client


networks:
  bcb-nt:
    driver: bridge
