server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${CLIENT_DB:localhost}:5432/clients
    username: root
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
